# Generated by Django 4.1.13 on 2024-03-17 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 19, 36, 40, 54875, tzinfo=datetime.timezone.utc)),
        ),
    ]
