# Generated by Django 4.1.13 on 2024-03-04 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 23, 50, 51, 628073, tzinfo=datetime.timezone.utc)),
        ),
    ]
