# Generated by Django 4.1.13 on 2024-03-11 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 6, 15, 50, 88385, tzinfo=datetime.timezone.utc)),
        ),
    ]
